### ISSUE TITLE
refactor parts/libvirt and parts/kvm out of this role entirely

### ISSUE THREAD

**Issue by halcyondude** [redhat-openstack/ansible-role-tripleo-image-build#2]
The image building role depends on a few packages from kvm and libvirt.  The existing role pulls these in via meta (good) pointing to parts/\* (bad).   Specifically it pulls in these packages and service:

https://github.com/redhat-openstack/ansible-role-tripleo-image-build/blob/master/parts/libvirt/defaults/main.yml

and does some basic KVM config operations here:

https://github.com/redhat-openstack/ansible-role-tripleo-image-build/blob/master/parts/kvm/tasks/main.yml

This issue tracks migrating this out of this role --> something generic, so this role can remain clean/portable.

**Comment by trown** [comment]
If we always need these packages for this role, I am not sure we gain much by externalizing that dependency.

**Comment by halcyondude** [comment]
Done.
